### ISSUE TITLE
Lista things

### ISSUE THREAD

**Issue by vety010** [Apioframe/eln1-revived#24]
a) Sealed full-block cable for galactic craft and in general, so a) you can make space stations a bit easier, and place them underground - these should heat up REALLY SLOW because of ground being as big radiator
b) Electro potion stations - they would NOT use blaze powder to heat up but electricity! Why not?
c) Electro anvil - this one could support buildcraft's item system, and also it should not break or break really slow.
d) That one is kinda strange but can we add signal lasers? So laser block itself, laser receiver, laser repeater, direct laser to redstone converter, laser splitter/rotator. I don't have any really good use for those but it would be nice, also laser blocks could consume not only signal but also electricity

**Comment by qrmcat** [comment]
This could be split up into multiple issues.

The sealed full-block cable is an OK idea.
The electro potion stations: nope, since blaze powder is an ingredient.
Electro anvil: I could only imagine this like an automated hammer on an anvil. 
signal lasers: We already have microwave transmitters/receivers, and plan on having signal cables on poles (see #9 )
